services:
  - type: web
    runtime: node
    name: laugh-tale-web
    buildCommand: bun install && bun --bun run build
    startCommand: bun --bun run start
    envVars:
      - key: BUN_VERSION
        value: "1.4.2"
      - key: NITRO_PRESET
        value: render-com
      - key: HOST
        value: 0.0.0.0
